#!/bin/sh

sudo aptitude -y install git vim zsh ruby python python3 python-virtualenv tmux build-essential openssl libreadline6 libreadline6-dev curl zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion cmake
