#!/bin/bash

if [ -d ~/.skel ]
then
  echo "you already have a skeleton."
  exit
fi

hash git >/dev/null || {
  echo "git not installed"
  echo "assuming debian and installing git"
  sudo aptitude -y install git
}
  

echo "cloning skel into ~/.skel"
hash git >/dev/null && /usr/bin/env git clone https://github.com/ahdinosaur/skel.git ~/.skel || {
  echo "git still not installed"
  echo "git available here: http://git-scm.com/downloads"
  exit
}

cd ~/.skel
./run
