#!/bin/bash

if [ -d ~/.skel ]
then
  echo "you already have a skeleton."
  exit
fi

echo "installing deps"
wget --no-check-certificate https://github.com/ahdinosaur/skel/raw/master/deps -O - | sh
  

echo "cloning skel into ~/.skel"
hash git >/dev/null && /usr/bin/env git clone https://github.com/ahdinosaur/skel.git ~/.skel || {
  echo "git still not installed"
  echo "git available here: http://git-scm.com/downloads"
  exit
}

cd "~/.skel"

echo "installing rvm before installing configs..."
cd "modules/"
"./rvm.sh"
cd "../"

echo "installing configs..."
cd "config/"
source ~/.rvm/scripts/rvm
gem install bundler
bundle
bundle exec rake install
cd "../"

echo "installing modules..."
cd "modules/"
for module in $(find . -maxdepth 1 -mindepth 1 -not -name rvm.sh -not -name .git -not -name README.md -print)
do
    "$module"
done
cd "../"
