#!/usr/bin/env python

from glob import glob
import os
import os.path
import subprocess

# install virtualenv
# install 

# install environment
os.chdir("env/")
for environment in glob("*"):
    subprocess.call(os.path.join(os.getcwd(), environment))
os.chdir("../")

# install configs
os.chdir("config/")
subprocess.call("/usr/bin/gem install bundler")
subprocess.call("bundle")
subprocess.call("bundle exec rake install")
os.chdir("../")

# install modules
os.chdir("modules/")
for module in glob("*"):
    subprocess.call(os.path.join(os.getcwd(), module))
os.chdir("../")
