#!/bin/bash

echo "installing environment"
cd "env/"
for environment in $(ls)
do
    "./$environment"
done
cd "../"

echo "installing configs..."
cd "config/"
source ~/.rvm/scripts/rvm
gem install bundler
bundle
bundle exec rake install
cd "../"

echo "installing modules..."
cd "modules/"
for module in glob("*"):
    "./$module"
cd "../"
