#!/bin/sh

cd "config/"

echo "uninstalling dotfiles"
source ~/.rvm/scripts/rvm
gem install bundler
bundle
bundle exec rake uninstall

echo "updating dotfiles"
git pull -u origin master

echo "reinstalling dotfiles"
bundle exec rake install

cd "../"
